// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/dashboard/:id";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./dashboard/[id]/page.jsx": {
    id: "dashboard/[id]/page";
    page: "/dashboard/:id";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "dashboard/page": typeof import("./src/app/./dashboard/page.jsx");
  "dashboard/[id]/page": typeof import("./src/app/./dashboard/[id]/page.jsx");
};